registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
    REGISTRY_HTTP_TLS_KEY: /certs/server.key
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
  volumes:
    - /Users/bmayuri/Documents/workspace/docker_images/data:/var/lib/registry
    - /Users/bmayuri/Documents/workspace/docker_images/registry/certs:/certs
